# Generated by Django 4.1.5 on 2023-02-08 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
