# Generated by Django 4.1.7 on 2023-04-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_application_sposob_svarki"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="welder_date_birth",
            field=models.DateTimeField(verbose_name="Дата рождения сварщика"),
        ),
    ]
