# Generated by Django 4.1.7 on 2023-04-27 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_application_welder_date_birth"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="sheet_butt_weld_max_position",
            new_name="sheet_butt_weld_position",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="sheet_fillet_weld_max_position",
            new_name="sheet_fillet_weld_position",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="tube_butt_weld_max_position",
            new_name="tube_butt_weld_position",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="tube_fillet_weld_max_position",
            new_name="tube_fillet_weld_position",
        ),
    ]
