# Generated by Django 4.1.7 on 2023-04-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "main",
            "0005_rename_sheet_butt_weld_max_position_application_sheet_butt_weld_position_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="welder_date_birth",
            field=models.DateField(
                null=True, verbose_name="Дата рождения сварщика"),
        ),
    ]
