# Generated by Django 4.1.7 on 2023-04-28 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_aplic_status_weld_select_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="aplic_status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.aplic_status",
                verbose_name="Статус заявки",
            ),
        ),
    ]
