# Generated by Django 4.1.7 on 2023-04-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_alter_application_sheet_butt_weld"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="sheet_butt_weld",
            field=models.CharField(
                choices=[("0", "Не заявлено"), ("1", "Заявлено")],
                max_length=15,
                null=True,
                verbose_name="Лист - Стыковой шов",
            ),
        ),
    ]
