# Generated by Django 4.1.7 on 2023-04-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_alter_application_sheet_butt_weld"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="welder_card_id",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Номер удостоверения сварщика"
            ),
        ),
    ]
