# Generated by Django 4.1.7 on 2023-05-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_application_aplic_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material_Electrode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Сертификат №"
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Марка"),
                ),
                (
                    "diameter",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Диаметр"),
                ),
                (
                    "date",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Дата"),
                ),
            ],
            options={
                "verbose_name": "Материал вспомогательный - Электрод",
                "verbose_name_plural": "Материал вспомогательный - Электрод",
            },
        ),
        migrations.CreateModel(
            name="Material_Flux",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Сертификат №"
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Дата"),
                ),
                (
                    "brand",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Марка"),
                ),
            ],
            options={
                "verbose_name": "Материал вспомогательный - Флюс",
                "verbose_name_plural": "Материал вспомогательный - Флюс",
            },
        ),
        migrations.CreateModel(
            name="Material_Plate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thickness",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Толщина листа"
                    ),
                ),
                (
                    "group_of_material",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Группа материала"
                    ),
                ),
                (
                    "steel_grade",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Марка стали"
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Сертификат №"
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Дата"),
                ),
            ],
            options={
                "verbose_name": "Материал основной - Лист",
                "verbose_name_plural": "Материал основной - Лист",
            },
        ),
        migrations.CreateModel(
            name="Material_Rod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Сертификат №"
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Дата"),
                ),
                (
                    "brand",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Марка"),
                ),
                (
                    "diameter",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Диаметр"),
                ),
            ],
            options={
                "verbose_name": "Материал вспомогательный - Пруток",
                "verbose_name_plural": "Материал вспомогательный - Пруток",
            },
        ),
        migrations.CreateModel(
            name="Material_Tube",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diameter",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Диаметр трубы"
                    ),
                ),
                (
                    "thickness",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Толщина стенки"
                    ),
                ),
                (
                    "group_of_material",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Группа материала"
                    ),
                ),
                (
                    "steel_grade",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Марка стали"
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Сертификат №"
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Дата"),
                ),
            ],
            options={
                "verbose_name": "Материал основной - Труба",
                "verbose_name_plural": "Материал основной - Труба",
            },
        ),
        migrations.CreateModel(
            name="Material_Wire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Сертификат №"
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Дата"),
                ),
                (
                    "brand",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Марка"),
                ),
                (
                    "diameter",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Диаметр"),
                ),
            ],
            options={
                "verbose_name": "Материал вспомогательный - Проволока",
                "verbose_name_plural": "Материал вспомогательный - Проволока",
            },
        ),
    ]
