# Generated by Django 4.1.7 on 2023-05-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_material_electrode_material_flux_material_plate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aplic_status",
            name="aplic_num",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Обозначение статуса заявки"
            ),
        ),
    ]
