# Generated by Django 4.1.7 on 2023-05-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_application_end_date_application_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="gpn",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Подведомственные Госпромнадзору МЧС РБ",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="mas",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Подведомственные Министерству архитектуры и строительства РБ",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="org_adress_f",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Адрес организации (фактический)",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="org_adress_ur",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Адрес организации (юридический)",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="org_bank_adress",
            field=models.CharField(
                max_length=2000, null=True, verbose_name="Адрес банка"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="org_bank_kod",
            field=models.CharField(
                max_length=2000, null=True, verbose_name="Код банка"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="org_bank_name",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Банк"),
        ),
        migrations.AlterField(
            model_name="application",
            name="org_bank_okpo",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="ОКПО"),
        ),
        migrations.AlterField(
            model_name="application",
            name="org_bank_rs",
            field=models.CharField(
                max_length=2000, null=True, verbose_name="Рассчетный счет"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="org_bank_unp",
            field=models.CharField(
                max_length=2000, null=True, verbose_name="УНП"),
        ),
        migrations.AlterField(
            model_name="application",
            name="org_contakt_data",
            field=models.CharField(
                max_length=2000, null=True, verbose_name="Контактные данные"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="org_deystvie",
            field=models.CharField(
                max_length=2000, null=True, verbose_name="Действует на основании"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="org_director_name",
            field=models.CharField(
                max_length=2000, null=True, verbose_name="Ф.И.О. руководителя"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="org_name",
            field=models.CharField(
                max_length=2000, null=True, verbose_name="Наименование организации"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="sheet_butt_weld_max_thickn",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Максимальная толщина листа - Стыковой шов",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="sheet_butt_weld_min_thickn",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Минимальная толщина листа - Стыковой шов",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="sheet_butt_weld_position",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Пространственное положение листа - Стыковой шов",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="sheet_butt_weld_steel_grade",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Марка стали листа - Стыковой шов",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="sheet_fillet_weld_max_thickn",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Максимальная толщина листа - Угловой шов",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="sheet_fillet_weld_min_thickn",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Минимальная толщина листа - Угловой шов",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="sheet_fillet_weld_position",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Пространственное положение листа - Угловой шов",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="sheet_fillet_weld_steel_grade",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Марка стали листа - Угловой шов",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="tube_butt_weld_max_diam",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Максимальный диаметр трубы - Стыковой шов",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="tube_butt_weld_max_thickn",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Максимальная толщина стенки трубы - Стыковой шов",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="tube_butt_weld_min_diam",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Минимальный диаметр трубы - Стыковой шов",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="tube_butt_weld_min_thickn",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Минимальная толщина стенки трубы - Стыковой шов",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="tube_butt_weld_position",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Пространственное положение  трубы - Стыковой шов",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="tube_butt_weld_steel_grade",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Марка стали трубы - Стыковой шов",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="tube_fillet_weld_max_diam",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Максимальный диаметр трубы - Угловой шов",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="tube_fillet_weld_max_thickn",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Максимальная толщина стенки трубы - Угловой шов",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="tube_fillet_weld_min_diam",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Минимальный диаметр трубы - Угловой шов",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="tube_fillet_weld_min_thickn",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Минимальная толщина стенки трубы - Угловой шов",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="tube_fillet_weld_position",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Пространственное положение  трубы - Угловой шов",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="tube_fillet_weld_steel_grade",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Марка стали трубы - Угловой шов",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="user_email",
            field=models.CharField(
                max_length=2000, null=True, verbose_name="Электронная почта заявителя"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="user_fio",
            field=models.CharField(
                max_length=2000, null=True, verbose_name="ФИО заявителя"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="user_telephon",
            field=models.CharField(
                max_length=2000, null=True, verbose_name="Телефон заявителя"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="welder_brand",
            field=models.CharField(
                max_length=2000, null=True, verbose_name="Клеймо сварщика"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="welder_card_id",
            field=models.CharField(
                max_length=2000, null=True, verbose_name="Номер удостоверения сварщика"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="welder_date_birth",
            field=models.CharField(
                max_length=2000, null=True, verbose_name="Дата рождения сварщика"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="welder_name",
            field=models.CharField(
                max_length=2000, null=True, verbose_name="Имя сварщика"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="welder_passport",
            field=models.CharField(
                max_length=2000, null=True, verbose_name="Паспорт сварщика"
            ),
        ),
        migrations.AlterField(
            model_name="material_electrode",
            name="date",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="material_flux",
            name="date",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="material_plate",
            name="certificate_number",
            field=models.CharField(
                max_length=2000, null=True, verbose_name="Сертификат №"
            ),
        ),
        migrations.AlterField(
            model_name="material_plate",
            name="date",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="material_plate",
            name="steel_grade",
            field=models.CharField(
                max_length=2000, null=True, verbose_name="Марка стали"
            ),
        ),
        migrations.AlterField(
            model_name="material_rod",
            name="date",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="material_tube",
            name="certificate_number",
            field=models.CharField(
                max_length=2000, null=True, verbose_name="Сертификат №"
            ),
        ),
        migrations.AlterField(
            model_name="material_tube",
            name="date",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="material_tube",
            name="steel_grade",
            field=models.CharField(
                max_length=2000, null=True, verbose_name="Марка стали"
            ),
        ),
        migrations.AlterField(
            model_name="material_wire",
            name="date",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="welding_method",
            name="weld_name",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Полное название способа сварки",
            ),
        ),
    ]
