# Generated by Django 4.1.7 on 2023-05-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_alter_application_gpn_alter_application_mas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="chef_kom_fio",
            field=models.CharField(
                max_length=2000, null=True, verbose_name="Имя председателя комиссии"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="chef_kom_pos",
            field=models.CharField(
                max_length=2000,
                null=True,
                verbose_name="Должность председателя комиссии",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="kom_fio",
            field=models.CharField(
                max_length=2000, null=True, verbose_name="Имя члена комиссии"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="kom_pos",
            field=models.CharField(
                max_length=2000, null=True, verbose_name="Должность члена комиссии"
            ),
        ),
    ]
