# Generated by Django 4.1.7 on 2023-05-10 10:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_application_chef_kom_fio_application_chef_kom_pos_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="sheet_butt_weld",
        ),
        migrations.RemoveField(
            model_name="application",
            name="sheet_fillet_weld",
        ),
        migrations.RemoveField(
            model_name="application",
            name="tube_butt_weld",
        ),
        migrations.RemoveField(
            model_name="application",
            name="tube_fillet_weld",
        ),
    ]
