# Generated by Django 4.1.7 on 2023-05-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_alter_application_weld_main_material_plate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="start_date",
            field=models.CharField(
                default="NULL",
                max_length=2000,
                null=True,
                verbose_name="Дата начала контроля",
            ),
        ),
    ]
